name: Generate NuGet Dependency Graph

on:
  push:
    branches:
      - main

jobs:
  generate-nupkg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release

      - name: Publish NuGet package
        run: dotnet nuget push <your_nupkg_file>.nupkg --source <your_nuget_source> --api-key ${{ secrets.NUGET_API_KEY }}
